---
name: safari_rally
description: Safari Rally Environment Team application
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.15.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  cloud_firestore: ^3.1.17
  fluttertoast: ^8.0.9
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  dio: ^4.0.0
  flutter_polyline_points: ^1.0.0
  google_maps_flutter: ^2.1.7
  geolocator: ^8.2.1
  location: 4.4.0
  conditional_questions: ^2.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
  assets:
    - assets/images/
  uses-material-design: true
  fonts:
  - family: Yessir
    fonts:
    - asset: assets/MyFlutterApp.ttf
