---
name: safari_rally
description: Safari Rally Environment Team application
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.15.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.10
  fluttertoast: ^8.0.9
  firebase_auth: ^3.3.11
  firebase_core: ^1.13.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  assets:
  - assets/images/
  uses-material-design: true
  fonts:
  - family: Yessir
    fonts:
    - asset: assets/MyFlutterApp.ttf
